// <auto-generated />
using System;
using AudioAnalytic.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudioAnalytic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210623162352_createDb")]
    partial class createDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AudioAnalytic.Entities.PublicTest", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("AgeRaw")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Result")
                        .HasColumnType("int");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Uuid");

                    b.ToTable("PublicTest");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.PublicTrain", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("AgeRaw")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Result")
                        .HasColumnType("int");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Uuid");

                    b.ToTable("PublicTrain");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.TestFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootFile")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RootFile");

                    b.ToTable("TestFeature");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.TrainFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootFile")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RootFile");

                    b.ToTable("TrainFeature");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.TestFeature", b =>
                {
                    b.HasOne("AudioAnalytic.Entities.PublicTest", "PublicTest")
                        .WithMany("TestFeatures")
                        .HasForeignKey("RootFile");

                    b.Navigation("PublicTest");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.TrainFeature", b =>
                {
                    b.HasOne("AudioAnalytic.Entities.PublicTrain", "PublicTrain")
                        .WithMany("TrainFeatures")
                        .HasForeignKey("RootFile");

                    b.Navigation("PublicTrain");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.PublicTest", b =>
                {
                    b.Navigation("TestFeatures");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.PublicTrain", b =>
                {
                    b.Navigation("TrainFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
