// <auto-generated />
using System;
using AudioAnalytic.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudioAnalytic.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AudioAnalytic.Entities.AudioDetail", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Uuid");

                    b.ToTable("AudioDetail");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.FileFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSpec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RootFile")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RootFile");

                    b.ToTable("FileFeature");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.FileFeature", b =>
                {
                    b.HasOne("AudioAnalytic.Entities.AudioDetail", "AudioDetail")
                        .WithMany("FileFeatures")
                        .HasForeignKey("RootFile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioDetail");
                });

            modelBuilder.Entity("AudioAnalytic.Entities.AudioDetail", b =>
                {
                    b.Navigation("FileFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
